language: node_js
node_js:
- stable
cache: npm
deploy:
  provider: npm
  email: navid@uni-bremen.de
  api_key:
    secure:
  on:
    tags: true
    repo: code-iai/eslint-config-openease
    branch: release
