language: node_js
node_js:
- stable
cache: npm

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      branches:
        only:
          - master
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
